site_name: EPO Tech Team
nav:
  - "index.md"
  - "cloud-services/index.md"
  - "useful-apps/index.md"
  - "global-dependencies/index.md"
  - "project-dependencies/index.md"
  - "github/index.md"
  - "stack/index.md"
  - "Active Projects":
    - "active-projects/main-site.md"
    - "active-projects/investigations/index.md"
    - "active-projects/skyviewer/index.md"
  - "Legacy Projects":
    - "legacy-projects/legacy-main-site.md"
    - "legacy-projects/ed-hub.md"
theme: 
  name: material
  collapse_navigation: False
  features:
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.expand
  favicon: img/favicon.ico
  logo: img/logo.svg
  font:
    text: Source Sans Pro
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - styles/extra.css
plugins:
  - i18n:
      material_alternate: true
      default_language: en
      languages:
        en: 
          name: English
          site_name: EPO Tech Team
        es: 
          name: Español
          site_name: EPO Equipo de Tecnología
  - search:
      lang:
        - en
        - es